# Generated by Django 3.0.3 on 2020-05-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreview',
            old_name='parent',
            new_name='child',
        ),
    ]
