# Generated by Django 3.0.3 on 2020-05-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200516_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreview',
            old_name='child',
            new_name='parent',
        ),
    ]
