# Generated by Django 3.0.3 on 2020-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200516_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreview',
            name='parent',
        ),
        migrations.AddField(
            model_name='commentreview',
            name='childs',
            field=models.ManyToManyField(null=True, related_name='_commentreview_childs_+', to='comments.CommentReview'),
        ),
    ]
