# Generated by Django 3.0.3 on 2020-05-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200516_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreview',
            name='childs',
        ),
        migrations.AddField(
            model_name='commentreview',
            name='childs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.CommentReview'),
        ),
    ]
