# Generated by Django 3.0.3 on 2020-05-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20200516_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreview',
            old_name='childs',
            new_name='parent',
        ),
    ]
