# Generated by Django 3.0.3 on 2020-05-16 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_delete_commentreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0007_auto_20200516_2259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentReview',
            new_name='Comment',
        ),
    ]
