# Generated by Django 3.0.3 on 2020-05-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20200516_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
