# Generated by Django 3.0.3 on 2020-05-17 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_commentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreview',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_comment', to='comments.CommentReview'),
        ),
        migrations.AlterField(
            model_name='commentreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment', to='comments.CommentReview'),
        ),
    ]
