# Generated by Django 3.0.3 on 2020-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20200517_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreview',
            name='child',
        ),
        migrations.RemoveField(
            model_name='commentreview',
            name='parent',
        ),
        migrations.AddField(
            model_name='commentreview',
            name='childs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_commentreview_childs_+', to='comments.CommentReview'),
        ),
    ]
