# Generated by Django 3.0.3 on 2020-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_commentreview_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreview',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='_commentreview_childs_+', to='comments.CommentReview'),
        ),
    ]
