# Generated by Django 3.0.3 on 2020-05-16 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20200516_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='review',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='reviews_down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='reviews_up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
