# Generated by Django 3.0.3 on 2020-05-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_commentreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReview',
        ),
    ]
