# Generated by Django 3.0.3 on 2020-05-15 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_remove_product_quantity'),
        ('cart', '0002_auto_20200515_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartProduct',
        ),
    ]
