# Generated by Django 3.0.3 on 2020-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200515_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
