# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-06 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_type',
            new_name='action_object',
        ),
    ]
