# Generated by Django 3.0.3 on 2020-05-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
